package tr.tutorial.JSF_Tutorial;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

public class UserBean {
	String bookmarkURL;
	 
	public String getBookmarkURL() {
		return bookmarkURL;
	}
 
	public void setBookmarkURL(String bookmarkURL) {
		this.bookmarkURL = bookmarkURL;
	}
	private String userName;
	private String password;
	private String answer = "I'm Hidden value!";
	private String address;
	private boolean rememberMe;
	public boolean isRememberMe() {
		return rememberMe;
	}

	public void setRememberMe(boolean rememberMe) {
		this.rememberMe = rememberMe;
	}

	public String[] getFavNumber1() {
		return favNumber1;
	}

	public void setFavNumber1(String[] favNumber1) {
		this.favNumber1 = favNumber1;
	}

	public String[] getFavNumber2() {
		return favNumber2;
	}

	public void setFavNumber2(String[] favNumber2) {
		this.favNumber2 = favNumber2;
	}

	public String[] getFavNumber3() {
		return favNumber3;
	}

	public void setFavNumber3(String[] favNumber3) {
		this.favNumber3 = favNumber3;
	}

	public String[] getFavNumber4() {
		return favNumber4;
	}

	public void setFavNumber4(String[] favNumber4) {
		this.favNumber4 = favNumber4;
	}


	private String[] favNumber1;
	private String[] favNumber2;
	private String[] favNumber3;
	private String[] favNumber4;
 
	//getter and setter methods...
 
	public String getFavNumber1InString() {
		return Arrays.toString(favNumber1);
	}
 
	//Generated by Array
	public String[] getFavNumber2Value() {
 
		favNumber2 = new String[5];
		favNumber2[0] = "Number2 - 1";
		favNumber2[1] = "Number2 - 2";
		favNumber2[2] = "Number2 - 3";
		favNumber2[3] = "Number2 - 4";
		favNumber2[4] = "Number2 - 5";
 
		return favNumber2;
	}
 
	public String getFavNumber2InString() {
		return Arrays.toString(favNumber2);
	}
 
 
	//Generated by Map
	private static Map<String,Object> number3Value;
	static{
		number3Value = new LinkedHashMap<String,Object>();
		number3Value.put("Number3 - 1", "1"); //label, value
		number3Value.put("Number3 - 2", "2");
		number3Value.put("Number3 - 3", "3");
		number3Value.put("Number3 - 4", "4");
		number3Value.put("Number3 - 5", "5");
	}
 
	public Map<String,Object> getFavNumber3Value() {
		return number3Value;
	}
 
	public String getFavNumber3InString() {
		return Arrays.toString(favNumber3);
	}
 
	//Generated by Object array
	public static class Number{
		public String numberLabel;
		public String numberValue;
 
		public Number(String numberLabel, String numberValue){
			this.numberLabel = numberLabel;
			this.numberValue = numberValue;
		}
 
		public String getNumberLabel(){
			return numberLabel;
		}
 
		public String getNumberValue(){
			return numberValue;
		}
 
	}
 
	public Number[] number4List;
 
	public Number[] getFavNumber4Value() {
 
		number4List = new Number[5];
		number4List[0] = new Number("Number4 - 1", "1");
		number4List[1] = new Number("Number4 - 2", "2");
		number4List[2] = new Number("Number4 - 3", "3");
		number4List[3] = new Number("Number4 - 4", "4");
		number4List[4] = new Number("Number4 - 5", "5");
 
		return number4List;
	}
 
	public String getFavNumber4InString() {
		return Arrays.toString(favNumber4);
	}
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	public String favColor1;
	public String favColor2;
	public String favColor3;
 
	//getter and setter methods 
 
	//Generated by Map
	private static Map<String,Object> color2Value;
	static{
		color2Value = new LinkedHashMap<String,Object>();
		color2Value.put("Color2 - Red", "Red"); //label, value
		color2Value.put("Color2 - Green", "Green");
		color2Value.put("Color3 - Blue", "Blue");
	}
 
	public Map<String,Object> getFavColor2Value() {
		return color2Value;
	}
 
	//Generated by Object array
	public static class Color{
		public String colorLabel;
		public String colorValue;
 
		public Color(String colorLabel, String colorValue){
			this.colorLabel = colorLabel;
			this.colorValue = colorValue;
		}
 
		public String getColorLabel(){
			return colorLabel;
		}
 
		public String getColorValue(){
			return colorValue;
		}
 
	}
 
	public Color[] color3List;
 
	public Color[] getFavColor3Value() {
 
		color3List = new Color[3];
		color3List[0] = new Color("Color3 - Red", "Red");
		color3List[1] = new Color("Color3 - Green", "Green");
		color3List[2] = new Color("Color3 - Blue", "Blue");
 
		return color3List;
	}

	public String getFavColor1() {
		return favColor1;
	}

	public void setFavColor1(String favColor1) {
		this.favColor1 = favColor1;
	}

	public String getFavColor2() {
		return favColor2;
	}

	public void setFavColor2(String favColor2) {
		this.favColor2 = favColor2;
	}

	public String getFavColor3() {
		return favColor3;
	}

	public void setFavColor3(String favColor3) {
		this.favColor3 = favColor3;
	}
	public String favYear1;
	public String favYear2;
	public String favYear3;
 
	//getter and setter methods
 
	//Generated by Map
	private static Map<String,Object> year2Value;
	static{
		year2Value = new LinkedHashMap<String,Object>();
		year2Value.put("Year2 - 2000", "2000"); //label, value
		year2Value.put("Year2 - 2010", "2010");
		year2Value.put("Year2 - 2020", "2020");
	}
 
	public Map<String,Object> getFavYear2Value() {
		return year2Value;
	}
 
	//Generated by Object array
	public static class Year{
		public String yearLabel;
		public String yearValue;
 
		public Year(String yearLabel, String yearValue){
			this.yearLabel = yearLabel;
			this.yearValue = yearValue;
		}
 
		public String getYearLabel(){
			return yearLabel;
		}
 
		public String getYearValue(){
			return yearValue;
		}
 
	}
 
	public Year[] year3List;
 
	public Year[] getFavYear3Value() {
 
		year3List = new Year[3];
		year3List[0] = new Year("Year3 - 2000", "2000");
		year3List[1] = new Year("Year3 - 2010", "2010");
		year3List[2] = new Year("Year3 - 2020", "2020");
 
		return year3List;
	}

	public String getFavYear1() {
		return favYear1;
	}

	public void setFavYear1(String favYear1) {
		this.favYear1 = favYear1;
	}

	public String getFavYear2() {
		return favYear2;
	}

	public void setFavYear2(String favYear2) {
		this.favYear2 = favYear2;
	}

	public String getFavYear3() {
		return favYear3;
	}

	public void setFavYear3(String favYear3) {
		this.favYear3 = favYear3;
	}
	public String[] favFood1;
	public String[] favFood2;
	public String[] favFood3;
 
	//getter and setter methods...
 
	public String getFavFood1InString() {
		return Arrays.toString(favFood1);
	}
 
	public String getFavFood2InString() {
		return Arrays.toString(favFood2);
	}
 
	public String getFavFood3InString() {
		return Arrays.toString(favFood3);
	}
 
	//Generated by Map
	private static Map<String,Object> food2Value;
	static{
		food2Value = new LinkedHashMap<String,Object>();
		food2Value.put("Food2 - Fry Checken", "Fry Checken"); //label, value
		food2Value.put("Food2 - Tomyam Soup", "Tomyam Soup");
		food2Value.put("Food2 - Mixed Rice", "Mixed Rice");
	}
 
	public Map<String,Object> getFavFood2Value() {
		return food2Value;
	}
 
	//Generated by Object array
	public static class Food{
		public String foodLabel;
		public String foodValue;
 
		public Food(String foodLabel, String foodValue){
			this.foodLabel = foodLabel;
			this.foodValue = foodValue;
		}
 
		public String getFoodLabel(){
			return foodLabel;
		}
 
		public String getFoodValue(){
			return foodValue;
		}
 
	}
 
	public Food[] food3List;
 
	public Food[] getFavFood3Value() {
 
		food3List = new Food[3];
		food3List[0] = new Food("Food3 - Fry Checken", "Fry Checken");
		food3List[1] = new Food("Food3 - Tomyam Soup", "Tomyam Soup");
		food3List[2] = new Food("Food3 - Mixed Rice", "Mixed Rice");
 
		return food3List;
	}

	public String[] getFavFood1() {
		return favFood1;
	}

	public void setFavFood1(String[] favFood1) {
		this.favFood1 = favFood1;
	}

	public String[] getFavFood2() {
		return favFood2;
	}

	public void setFavFood2(String[] favFood2) {
		this.favFood2 = favFood2;
	}

	public String[] getFavFood3() {
		return favFood3;
	}

	public void setFavFood3(String[] favFood3) {
		this.favFood3 = favFood3;
	}
	public String text = "Hello {0}";
	public String htmlInput = "<input type=\"{0}\" {1} />";
	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getHtmlInput() {
		return htmlInput;
	}

	public void setHtmlInput(String htmlInput) {
		this.htmlInput = htmlInput;
	}
public String goLoginPage(){
		
		return "login";
		
	}
public String username;
public int age;

public String getUsername() {
	return username;
}
public void setUsername(String username) {
	this.username = username;
}
public int getAge() {
	return age;
}
public void setAge(int age) {
	this.age = age;
}
public String name;
public String country;

public String outcome(){
	
	FacesContext fc = FacesContext.getCurrentInstance();
	this.country = getCountryParam(fc);
	
	return "result";
}

//get value from "f:param"
public String getCountryParam(FacesContext fc){
	
	Map<String,String> params = fc.getExternalContext().getRequestParameterMap();
	return params.get("country");
	
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

public String getCountry() {
	return country;
}

public void setCountry(String country) {
	this.country = country;
}
public String nickname;

//action listener event
public void attrListener(ActionEvent event){

	nickname = (String)event.getComponent().getAttributes().get("username");

}



public String getNickname() {
	return nickname;
}

public void setNickname(String nickname) {
	this.nickname = nickname;
}
}
